logging:
  level:
    org.springframework: INFO
    com.vaadin.addon.pagination: DEBUG
server:
    port: 8888
    context-path: /yocojack-portal
endpoints.health.enabled: true
management:
   security:
      enabled: false
vaadin:
    servlet:
        close-idle-sessions: true
        productionMode: true
        heartbeatInterval: 100000
konstant:
    rule1: Over 21
    rule2: Ties
    rule3: Rank by Suits
    base_url: https://s3-eu-west-1.amazonaws.com/yoco-testing/tests.json 
    